### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by fredrikhgrelland** [gugalnikov/presto-consul-connect#2]
2020-06-16T19:46:23.657Z	INFO	main	io.prestosql.server.PluginManager	Installing io.github.gugalnikov.prestosql.plugin.consulconnect.ConsulConnectPlugin
2020-06-16T19:46:23.658Z	ERROR	main	io.prestosql.server.Server	com/google/common/collect/ImmutableList
java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at io.github.gugalnikov.prestosql.plugin.consulconnect.ConsulConnectPlugin.getCertificateAuthenticatorFactories(ConsulConnectPlugin.java:26)
	at io.prestosql.server.PluginManager.installPluginInternal(PluginManager.java:227)
	at io.prestosql.server.PluginManager.installPlugin(PluginManager.java:176)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:170)
	at io.prestosql.server.PluginManager.loadPlugin(PluginManager.java:158)
	at io.prestosql.server.PluginManager.loadPlugins(PluginManager.java:139)
	at io.prestosql.server.Server.doStart(Server.java:112)
	at io.prestosql.server.Server.lambda$start$0(Server.java:69)
	at io.prestosql.$gen.Presto_334____20200616_194551_1.run(Unknown Source)
	at io.prestosql.server.Server.start(Server.java:69)
	at io.prestosql.server.PrestoServer.main(PrestoServer.java:39)
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at io.prestosql.server.PluginClassLoader.loadClass(PluginClassLoader.java:89)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 11 more

**Comment by fredrikhgrelland** [comment]
fixed in 1.0.3-with-dependency-jars
